### ISSUE TITLE
trakio company support (group, identify)

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-trakio#1]
_From @sperand-io on January 20, 2015 22:42_

:( https://github.com/segmentio/analytics.js-integrations/blob/trakio/channels/lib/trakio/index.js#L120-L121

from a customer:

> we would like to track the Company name and for this to map to company in trak.io. We tried to use Group but doesn't map to Company in trak.io 

Looks like they have several methods related to this. I haven't distilled the best abstraction or anything but this should definitely be on our radar and is worth looking into — companies have become a core part of the trak.io featureset!

**details:**
- http://docs.trak.io/company_id.html
- http://docs.trak.io/company.html
- `company` subhead here: http://docs.trak.io/track.html

@amillet89 @ndhoule @harrietgrace 

_Copied from original issue: segmentio/analytics.js-integrations#504_

**Comment by ndhoule** [comment]
_From @f2prateek on February 5, 2015 1:40_

I've seen company in Intercom and a couple of other integrations, we should probably do the same here.

**Comment by hankim813** [comment]
added to jira for internal traige
